before_install:
  - sudo rm -f /etc/mavenrc
  - export M2_HOME=/usr/local/maven
  - export MAVEN_OPTS="-Dmaven.repo.local=$HOME/.m2/repository -Xms1024m -Xmx3072m"
  - export HTTP_LOG_CONTROLLER_ERROR_STACK_TRACE=false
jdk:
 - openjdk8
language: java
sudo: required
services:
  - docker
script: 
  - mvn clean install -DskipTests
  - ls application/target
  
after_success:
  - ls -lh application/target/* 
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh application/target/* 

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
